server:
  port: 10000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/studysecurity
    username: study
    password: 0910

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        use_sql_comments: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  security:
#    user:
#      name: "user"
#      password: "1234"